#ifndef APPS_PELICAN_BOARD_BLUEPILL_INC_BOARD_H_
#define APPS_PELICAN_BOARD_BLUEPILL_INC_BOARD_H_

#include "stm32f1xx_hal.h"

#define BOARD_CARS_RED() do { \
      HAL_GPIO_WritePin(CARS_YELLOW_GPIO_Port, CARS_YELLOW_Pin, GPIO_PIN_RESET); \
      HAL_GPIO_WritePin(CARS_GREEN_GPIO_Port, CARS_GREEN_Pin, GPIO_PIN_RESET); \
      HAL_GPIO_WritePin(CARS_RED_GPIO_Port, CARS_RED_Pin, GPIO_PIN_SET); \
} while(0)

#define BOARD_CARS_GREEN() do { \
      HAL_GPIO_WritePin(CARS_RED_GPIO_Port, CARS_RED_Pin, GPIO_PIN_RESET); \
      HAL_GPIO_WritePin(CARS_YELLOW_GPIO_Port, CARS_YELLOW_Pin, GPIO_PIN_RESET); \
      HAL_GPIO_WritePin(CARS_GREEN_GPIO_Port, CARS_GREEN_Pin, GPIO_PIN_SET); \
} while(0)

#define BOARD_CARS_YELLOW() do { \
      HAL_GPIO_WritePin(CARS_RED_GPIO_Port, CARS_RED_Pin, GPIO_PIN_RESET); \
      HAL_GPIO_WritePin(CARS_GREEN_GPIO_Port, CARS_GREEN_Pin, GPIO_PIN_RESET); \
      HAL_GPIO_WritePin(CARS_YELLOW_GPIO_Port, CARS_YELLOW_Pin, GPIO_PIN_SET); \
} while(0)

#define BOARD_PEDS_DONT_WALK() \
	HAL_GPIO_WritePin(PEDESTRIAN_WALK_GPIO_Port, PEDESTRIAN_WALK_Pin, GPIO_PIN_RESET)

#define BOARD_PEDS_WALK() \
	HAL_GPIO_WritePin(PEDESTRIAN_WALK_GPIO_Port, PEDESTRIAN_WALK_Pin, GPIO_PIN_SET)

#endif /* APPS_PELICAN_BOARD_BLUEPILL_INC_BOARD_H_ */
