#ifndef APPS_PRODCONS_BOARD_NATIVE_INC_BOARD_H_
#define APPS_PRODCONS_BOARD_NATIVE_INC_BOARD_H_

#define BOARD_WRITE_ACTUATOR() ESM_PRINTF("BOARD_WRITE_ACTUATOR\r\n")
#define BOARD_READ_SENSOR() ESM_PRINTF("BOARD_READ_SENSOR\r\n")

#endif /* APPS_PRODCONS_BOARD_NATIVE_INC_BOARD_H_ */
