#ifndef APPS_PRODCONS_BOARD_NATIVE_INC_BOARD_H_
#define APPS_PRODCONS_BOARD_NATIVE_INC_BOARD_H_

#define BOARD_TX() ESM_PRINTF("BOARD_TX\r\n")
#define BOARD_RX() ESM_PRINTF("BOARD_RX\r\n")

#endif /* APPS_PRODCONS_BOARD_NATIVE_INC_BOARD_H_ */
