#ifndef APPS_PRODCONS_BOARD_BLUEPILL_INC_BOARD_H_
#define APPS_PRODCONS_BOARD_BLUEPILL_INC_BOARD_H_

#define BOARD_WRITE_ACTUATOR()
#define BOARD_READ_SENSOR()

#endif /* APPS_PRODCONS_BOARD_BLUEPILL_INC_BOARD_H_ */
