#ifndef APPS_BLINK_BOARD_BLUEPILL_INC_BOARD_H_
#define APPS_BLINK_BOARD_BLUEPILL_INC_BOARD_H_

#define BOARD_LED_ON() \
	ESM_PRINTF("BLINK_LED:ON\r\n")

#define BOARD_LED_OFF() \
	ESM_PRINTF("BLINK_LED:OFF\r\n")

#endif /* APPS_BLINK_BOARD_BLUEPILL_INC_BOARD_H_ */
