#ifndef APPS_DCF77_BLINK_BOARD_BLUEPILL_INC_BOARD_H_
#define APPS_DCF77_BOARD_BLUEPILL_INC_BOARD_H_

#define DCF77_BIN_EVERY	(10UL)
#define DCF77_BIN_SIZE	(ESM_TICKS_PER_SEC/DCF77_BIN_EVERY)

#define BOARD_DEBUG_OUT()
#define BOARD_LED_FILTERED_ON()
#define BOARD_LED_FILTERED_OFF()

#endif /* APPS_DCF77_BOARD_BLUEPILL_INC_BOARD_H_ */
